import { Color } from "@/types";

export const TEXT_COLOR_MAPPING: Record<Color, string> = {
  primary: "text-primary",
  "primary-foreground": "text-primary-foreground",
  "primary-background": "text-primary-background",
  "primary-hover": "text-primary-hover",
  secondary: "text-secondary",
  "secondary-foreground": "text-secondary-foreground",
  "secondary-background": "text-secondary-background",
  "secondary-hover": "text-secondary-hover",
  danger: "text-danger",
  "danger-foreground": "text-danger-foreground",
  "danger-background": "text-danger-background",
  "danger-hover": "text-danger-hover",
  gray: "text-gray",
  "gray-foreground": "text-gray-foreground",
  "gray-background": "text-gray-background",
  "gray-hover": "text-gray-hover",
  black: "text-black",
  white: "text-white",
  success: "text-success",
  "success-foreground": "text-success-foreground",
  "success-background": "text-success-background",
  "success-hover": "text-success-hover",
  info: "text-info",
  "info-foreground": "text-info-foreground",
  "info-background": "text-info-background",
  "info-hover": "text-info-hover",
  warning: "text-warning",
  "warning-foreground": "text-warning-foreground",
  "warning-background": "text-warning-background",
  "warning-hover": "text-warning-hover",
  currentcolor: "text-current",
};
