export type Size = "xs" | "sm" | "md" | "lg" | "xl";
export type Color =
  | "primary"
  | "primary-foreground"
  | "primary-background"
  | "primary-hover"
  | "secondary"
  | "secondary-foreground"
  | "secondary-background"
  | "secondary-hover"
  | "danger"
  | "danger-foreground"
  | "danger-background"
  | "danger-hover"
  | "gray"
  | "gray-foreground"
  | "gray-background"
  | "gray-hover"
  | "black"
  | "white"
  | "success"
  | "success-foreground"
  | "success-background"
  | "success-hover"
  | "info"
  | "info-foreground"
  | "info-background"
  | "info-hover"
  | "warning"
  | "warning-foreground"
  | "warning-background"
  | "warning-hover"
  | "currentcolor";

export type MainColor =
  | "primary"
  | "secondary"
  | "danger"
  | "gray"
  | "black"
  | "white"
  | "success"
  | "info"
  | "warning"
  | "gray";
